{{- $_ := (set .Values "comp" .Values.ui) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: ui
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: ui
      annotations:
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: API_URL
            value: {{ .Values.comp.conf.apiUrl | quote }}
          - name: UI_DOCS_API_LINK
            value: {{ .Values.comp.conf.docs.apiLink | quote }}
          - name: UI_DOCS_WHITELISTING_LINK
            value: {{ .Values.comp.conf.docs.whitelistingLink | quote }}
          - name: UI_DOCS_DISCOVERY_LINK
            value: {{ .Values.comp.conf.docs.discoveryLink | quote }}
          - name: UI_DOCS_AUDITROLE_LINK
            value: {{ .Values.comp.conf.docs.auditRoleLink | quote }}
          - name: UI_CONTACT_EMAIL
            value: {{ .Values.comp.conf.contact.email | quote }}
          - name: UI_CONTACT_SLACK
            value: {{ .Values.comp.conf.contact.slack | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
