{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportsgenerator.fullname" . }}
  labels:
    {{- include "reportsgenerator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "reportsgenerator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reportsgenerator.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "reportsgenerator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: waitfordb
          image: "{{ .Values.waitfordb.image.repository }}:{{ .Values.waitfordb.image.tag }}"
          imagePullPolicy: Always
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: "{{ .Values.db.host | default (include "postgresqlHost" .) }}"
          - name: PGPORT
            value: "{{ .Values.db.port }}"
      containers:
        {{- include "common-containers" . | nindent 8 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.containerPort }}"
          - name: PG_HOST
            value: "{{ .Values.db.host | default (include "postgresqlHost" .) }}"
          - name: PG_NAME
            value: "{{ .Values.db.name }}"
          - name: PG_USER
            value: "{{ .Values.db.user }}"
          - name: PG_PORT
            value: "{{ .Values.db.port }}"
          - name: PG_SSLMODE
            value: "{{ .Values.db.sslMode }}"
          {{- if .Values.db.ca }}
          - name: PG_CA_B64
            value: "{{ .Values.db.ca | b64enc }}"
          {{- end }}
          - name: LOG_LEVEL
            value: "{{ .Values.conf.logLevel }}"
          - name: SQS_QUEUE_ARN
            value: "{{ .Values.conf.queueArn }}"
          - name: SES_REGION
            value: "{{ .Values.conf.ses.region | default (include "region" .) }}"
          - name: SES_FROM
            value: "{{ .Values.conf.ses.from }}"
          - name: SES_CC
            value: "{{ .Values.conf.ses.cc }}"
          - name: SCAN_EMAIL_SUBJECT
            value: "{{ .Values.conf.generators.scan.emailSubject }}"
          - name: SCAN_S3_PUBLIC_BUCKET
            value: "{{ .Values.conf.generators.scan.publicBucket }}"
          - name: SCAN_S3_PRIVATE_BUCKET
            value: "{{ .Values.conf.generators.scan.privateBucket }}"
          - name: SCAN_GA_ID
            value: "{{ .Values.conf.generators.scan.gaId }}"
          - name: PERSISTENCE_ENDPOINT
            value: "{{ .Values.conf.persistenceEndpoint | default (include "persistenceEndpoint" .) }}"
          - name: RESULTS_ENDPOINT
            value: "{{ .Values.conf.resultsEndpoint | default (include "resultsEndpoint" .) }}"
          - name: SCAN_PROXY_ENDPOINT
            value: "{{ .Values.conf.generators.scan.proxyEndpoint | default (printf "https://%s" ( include "insights.hostname" . )) }}"
          - name: VULCAN_UI
            value: "{{ .Values.conf.generators.scan.vulcanUi | default (printf "https://%s/" ( include "ui.hostname" . )) }}"
          - name: SCAN_VIEW_REPORT
            value: "{{ .Values.conf.generators.scan.viewReport | default ( printf "https://%s/api/v1/report?team_id=%s&scan_id=%s" ( include "ui.hostname" . ) "%s" "%s") }}"
          {{- if .Values.conf.generators.scan.redirectUrl }}
          - name: SCAN_REDIRECT_URL
            value: "{{ .Values.conf.generators.scan.redirectUrl }}"
          {{- end }}
          - name: LIVEREPORT_EMAIL_SUBJECT
            value: "{{ .Values.conf.generators.livereport.emailSubject }}"
        {{- include "common-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "reportsgenerator.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- include "common-lifecycle" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- include "common-volumes" . | nindent 6}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
