{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crontinuous.fullname" . }}
  labels:
    {{- include "crontinuous.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crontinuous.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crontinuous.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "crontinuous.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- include "common-containers" . | nindent 8 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.containerPort }}"
          - name: AWS_REGION
            value: {{ .Values.conf.region | default (include "region" .) }}
          - name: CRONTINUOUS_BUCKET
            value: {{ .Values.conf.crontinuousBucket }}
          - name: VULCAN_API
            value: {{ .Values.conf.vulcanApi | default (include "vulcanApi" .) }}
          - name: VULCAN_USER
            value: {{ .Values.conf.vulcanUser }}
          - name: ENABLE_TEAMS_WHITELIST_SCAN
            value: {{ .Values.conf.enableTeamsWhitelistScan | quote }}
          - name: TEAMS_WHITELIST_SCAN
            value: {{ .Values.conf.teamsWhitelistScan | quote}}
          - name: ENABLE_TEAMS_WHITELIST_REPORT
            value: {{ .Values.conf.enableTeamsWhitelistReport | quote }}
          - name: TEAMS_WHITELIST_REPORT
            value: {{ .Values.conf.teamsWhitelistReport | quote }}
        {{- include "common-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "crontinuous.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- include "common-lifecycle" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- include "common-volumes" . | nindent 6}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
