{{- $_ := (set .Values "comp" .Values.vulndb) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulndb.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/secrets: {{ include "vulndb-secrets" . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PG_HOST
            value: {{ include "pg.host" . | quote }}
          - name: PG_NAME
            value: {{ include "pg.database" . | quote }}
          - name: PG_USER
            value: {{ include "pg.username" . | quote }}
          - name: PG_PORT
            value: {{ include "pg.port" . | quote }}
          - name: PG_SSLMODE
            value: {{ include "pg.sslMode" . | quote }}
          - name: PG_CA_B64
            value: {{ include "pg.b64ca" . | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: MAX_EVENT_AGE
            value: {{ .Values.comp.conf.maxEventAge | quote }}
          - name: SQS_QUEUE_ARN
            value: {{ tpl .Values.comp.conf.checksQueueArn . | quote }}
          {{- with .Values.comp.conf.sqsNumProcessors }}
          - name: SQS_NUMBER_OF_PROCESSORS
            value: {{ . | quote }}
          {{- end }}
          - name: SNS_TOPIC_ARN
            value: {{ tpl .Values.comp.conf.vulnsTopicArn . | quote }}
          - name: SNS_ENABLED
            value: {{ .Values.comp.conf.vulnsTopicEnabled | quote }}
          - name: RESULTS_URL
            value: {{ .Values.comp.conf.resultsUrl | default ( printf "https://%s" (include "results.fullname" .)) }}
          - name: RESULTS_INTERNAL_URL
            value: {{ .Values.comp.conf.resultsInternalUrl | default (include "results.url" .)| quote }}
          - name: KAFKA_ENABLED
            value: {{ .Values.comp.conf.kafka.enabled | quote }}
          - name: KAFKA_USER
            value: {{ .Values.comp.conf.kafka.username | quote }}
          - name: KAFKA_PASSWORD
            value: {{ .Values.comp.conf.kafka.password | quote }}
          - name: KAFKA_BROKER_URL
            value: {{ .Values.comp.conf.kafka.broker | quote }}
          - name: KAFKA_TOPIC
            value: {{ .Values.comp.conf.kafka.topic | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "vulndb.fullname" . }}
          volumeMounts:
          {{- include "common-deployment-volumeMounts" . | nindent 12 }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
