{{- $_ := (set .Values "comp" .Values.vulndb) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulndb.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: vulndb
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: vulndb
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: vulndb
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/vulndb/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PG_HOST
            value: {{ .Values.comp.db.host | default (include "postgresqlHost" .) | quote }}
          - name: PG_NAME
            value: {{ .Values.comp.db.name | quote }}
          - name: PG_USER
            value: {{ .Values.comp.db.user | quote }}
          - name: PG_PORT
            value: {{ .Values.comp.db.port | quote }}
          - name: PG_SSLMODE
            value: {{ .Values.comp.db.sslMode | quote }}
          {{- if .Values.comp.db.ca }}
          - name: PG_CA_B64
            value: {{ .Values.comp.db.ca | b64enc | quote }}
          {{- end }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: MAX_EVENT_AGE
            value: {{ .Values.comp.conf.maxEventAge | quote }}
          - name: SQS_QUEUE_ARN
            value: {{ .Values.comp.conf.checksQueueArn | quote }}
          - name: SNS_TOPIC_ARN
            value: {{ .Values.comp.conf.vulnsTopicArn | quote }}
          - name: RESULTS_URL
            value: {{ .Values.comp.conf.resultsUrl | default ( printf "https://%s" (include "results.fullname" .)) }}
          - name: RESULTS_INTERNAL_URL
            value: {{ .Values.comp.conf.resultsInternalUrl | default (include "results.url" .)| quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "vulndb.fullname" . }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
