{{- $_ := (set .Values "comp" .Values.vulndbapi) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulndbapi.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/vulndbapi/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: PG_HOST
            value: {{ include "pg.host" . | quote }}
          - name: PG_NAME
            value: {{ include "pg.database" . | quote }}
          - name: PG_USER
            value: {{ include "pg.username" . | quote }}
          - name: PG_PORT
            value: {{ include "pg.port" . | quote }}
          - name: PG_SSLMODE
            value: {{ include "pg.sslMode" . | quote }}
          - name: PG_CA_B64
            value: {{ include "pg.b64ca" . | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "vulndbapi.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
