{{- $_ := (set .Values "comp" .Values.redis) -}}
{{- if .Values.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: redis
      annotations:
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.comp.name }}
          {{- with .Values.comp.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        image: "{{ .Values.comp.image.repository }}:{{ .Values.comp.image.tag }}"
        imagePullPolicy: {{ .Values.comp.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ include "redis.fullname" . }}
        {{- range $name, $value := .Values.comp.extraEnv }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
          - name: {{ include "common-appPortName" . }}
            containerPort: {{ .Values.comp.containerPort }}
            protocol: TCP
      volumes:
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
