{{- $_ := (set .Values "comp" .Values.goaws) -}}
{{- if .Values.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goaws.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/config: {{ include "goaws-config" . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.comp.name }}
        {{- with .Values.comp.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.comp.image.repository }}:{{ .Values.comp.image.tag }}"
        imagePullPolicy: {{ .Values.comp.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.comp.containerPort }}
            protocol: TCP
        volumeMounts:
        {{- if .Values.comp.config }}
        - name: goaws-config
          mountPath: /app/conf
        {{- end }}
      volumes:
      {{- if .Values.comp.config }}
      - name: goaws-config
        configMap:
          name: {{ template "goaws.fullname" . }}
      {{- end }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
