{{- $_ := (set .Values "comp" .Values.insights) -}}
{{- if .Values.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insights.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/config: {{ include "insights-config" . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: insights-private
          {{- include "common-container" . | nindent 10 }}
          env:
            - name: AWS_REGION
              value: {{ .Values.comp.conf.region | default (include "region" . ) | quote }}
            - name: ACCESS_LOG
              value: {{ .Values.comp.conf.log | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.comp.conf.private.s3Bucket | quote }}
            - name: STRIP_PATH
              value: {{ .Values.comp.conf.private.prefix | quote }}
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: {{ .Values.comp.containerPort | quote }}
            {{- if and .Values.comp.meta.s3 .Values.minio.enabled }}
            - name: AWS_API_ENDPOINT
              value: {{ include "minio.url" . | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}
                  key: root-password
            {{- end }}
          ports:
            - name: private
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
        - name: insights-public
          {{- include "common-container" . | nindent 10 }}
          env:
            - name: AWS_REGION
              value: {{ .Values.comp.conf.region | default (include "region" . ) | quote }}
            - name: ACCESS_LOG
              value: {{ .Values.comp.conf.log | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.comp.conf.public.s3Bucket | quote }}
            - name: STRIP_PATH
              value: {{ .Values.comp.conf.public.prefix | quote }}
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: {{ add .Values.comp.containerPort 1 | quote }}
            {{- if and .Values.comp.meta.s3 .Values.minio.enabled }}
            - name: AWS_API_ENDPOINT
              value: {{ include "minio.url" . | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}
                  key: root-password
            {{- end }}
          ports:
            - name: public
              containerPort: {{ add .Values.comp.containerPort 1 }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end -}}
