apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "insights.fullname" . }}-proxy
  name: {{ include "insights.fullname" . }}-proxy
data:
  haproxy.cfg: |
    global
      daemon
      maxconn {{ .Values.proxy.maxconn | default 64 }}
      log stdout format raw daemon

    defaults
      mode http
      timeout connect {{ .Values.proxy.timeoutConnect | default "5s" }}
      timeout client {{ .Values.proxy.timeoutClient | default "25s" }}
      timeout server {{ .Values.proxy.timeoutServer | default "25s" }}
      timeout tunnel {{ .Values.proxy.timeoutTunnel | default "3600s" }}
      option  http-server-close

    {{- if .Values.proxy.cache }}
    cache small
      total-max-size 64     # mb
      max-age 240           # seconds
    {{- end }}

    frontend http
      bind *:{{ .Values.proxy.port | default 80 }}
      log global
      option httplog clf
    {{- if .Values.proxy.cache }}
      http-request cache-use small
      http-response cache-store small
    {{- end }}
      http-request capture req.hdr(Host) len 50
      http-request capture req.hdr(User-Agent) len 100
      {{- range .Values.conf.proxies }}
      {{- if .prefix }}
      use_backend {{ .name }} if { path -i -m beg {{ .prefix}} }
      {{- else }}
      default_backend {{ .name }}
      {{- end }}
      {{- end }}

    {{- $dot := . }}
    {{- range $i, $p := .Values.conf.proxies }}
    {{- $port := add $dot.Values.containerPort $i }}

    backend {{ $p.name }}
      server app 127.0.0.1:{{ $port }}
    {{- end }}

    frontend stats
      bind *:{{ .Values.proxy.metricsPort }}
      option http-use-htx
      http-request use-service prometheus-exporter if { path /metrics }
      monitor-uri {{ .Values.proxy.probePath }}
