{{- include "proxy-config-map" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
{{ include "api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "proxy-annotations" . | nindent 8 }}
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: waitfordb
          image: postgres:9.6.16-alpine
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: "{{ include "postgresqlHost" . }}"
          - name: PGPORT
            value: "{{ .Values.db.port }}"
      containers:
        {{- include "proxy-container" . | nindent 8 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.containerPort }}"
          - name: COOKIE_DOMAIN
            value: "{{ default .Values.global.domain .Values.conf.cookieDomain }}"
          - name: PG_HOST
            value: "{{ include "postgresqlHost" . }}"
          - name: PG_NAME
            value: "{{ .Values.db.name }}"
          - name: PG_USER
            value: "{{ .Values.db.user }}"
          - name: PG_PORT
            value: "{{ .Values.db.port }}"
          - name: PG_SSLMODE
            value: "{{ .Values.db.sslMode }}"
          {{- if .Values.db.ca }}
          - name: PG_CA_B64
            value: "{{ .Values.db.ca | b64enc }}"
          {{- end }}
          - name: LOG_LEVEL
            value: "{{ .Values.conf.log.level }}"
          - name: SAML_MEATADATA
            value: "{{ .Values.conf.saml.metadata }}"
          - name: SAML_ISSUER
            value: "{{ .Values.conf.saml.issuer }}"
          - name: SAML_CALLBACK
            value: "{{ .Values.conf.saml.callback | default ( printf "https://%s/api/v1/login/callback" ( include "api.hostname" . )) }}"
          - name: SAML_TRUSTED_DOMAINS
            value: {{ ( .Values.conf.saml.trustedDomains | quote ) | default ( printf "'[\"%s\"]'" ( include "api.hostname" . )) }}
          - name: SCANENGINE_URL
            value: "{{ .Values.conf.scanengineUrl | default  (include "scanengineUrl" .) }}"
          - name: SCHEDULER_URL
            value: "{{ .Values.conf.schedulerUrl | default  (include "crontinuousUrl" .) }}"
          - name: SQS_QUEUE_ARN
            value: "{{ .Values.conf.queueArn }}"
          - name: REPORTS_BASE_PATH
            value: "{{ .Values.conf.reports.basePath | default ( printf "https://%s" ( include "insights.hostname" . )) }}"
          - name: SES_REGION
            value: "{{ .Values.conf.ses.region | default .Values.global.region }}"
          - name: SES_CONFIG_SET
            value: "{{ .Values.conf.ses.configSet}}"
          - name: SES_SUBJECT
            value: "{{ .Values.conf.ses.subject }}"
          - name: SES_FROM
            value: "{{ .Values.conf.ses.from }}"
          - name: SES_CC
            value: "{{ .Values.conf.ses.cc }}"
          - name: PERSISTENCE_HOST
            value: "{{ .Values.conf.persistenceHost | default  (include "persistenceHost" .) }}"
          - name: VULNERABILITYDB_URL
            value: "{{ .Values.conf.vulnerabilityDbUrl }}"
          - name: GA_ID
            value: "{{ .Values.conf.gaId }}"
          - name: S3_PRIVATE_BUCKET
            value: "{{ .Values.conf.s3PrivateBucket }}"
          - name: S3_PUBLIC_BUCKET
            value: "{{ .Values.conf.s3PublicBucket }}"
          - name: PERSISTENCE_ENDPOINT
            value: "{{ .Values.conf.persistenceEndpoint | default (include "persistenceEndpoint" .)}}"
          - name: RESULTS_ENDPOINT
            value: "{{ .Values.conf.resultsEndpoint | default (include "resultsEndpoint" .)}}"
          - name: PROXY_ENDPOINT
            value: "{{ .Values.conf.reports.basePath | default ( printf "https://%s" ( include "insights.hostname" . )) }}"
          - name: VULCAN_UI
            value: "{{ .Values.conf.vulcanUi | default (printf "https://%s/" ( include "ui.hostname" . )) }}"
          - name: VIEW_REPORT
            value: "{{ .Values.conf.viewReport | default ( printf "https://%s/api/v1/report?team_id=%s&scan_id=%s" ( include "ui.hostname" . ) "%s" "%s") }}"
          - name: REDIRECT_URL
            value: "{{ .Values.conf.redirectUrl }}"
          # Security overview vars.
          - name: COMPANY_NAME
            value:  "{{ .Values.conf.general.companyName }}"
          - name: SUPPORT_EMAIL
            value: "{{ .Values.conf.general.supportEmail }}"
          - name: CONTACT_EMAIL
            value: "{{ .Values.conf.general.contactEmail }}"
          - name: CONTACT_CHANNEL
            value: "{{ .Values.conf.general.contactChannel }}"
          - name: DOCUMENTATION_LINK
            value: "{{ .Values.conf.general.documentationLink }}"
          - name: ROADMAP_LINK
            value: "{{ .Values.conf.general.roadmapLink }}"
          {{- if .Values.global.sqs.enabled}}
          - name: SQS_QUEUE_NAME
            value: "{{ .Values.conf.queueName }}"
          {{- end -}}
        {{- include "infra-envs-minio" . | nindent 10 -}}
        {{- include "infra-envs-sqs" . | nindent 10 -}}
        {{- range $name, $value := .Values.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "api.fullname" . }}
          ports:
            - name: {{ ternary "app" "http" .Values.proxy.enabled }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probeInitialDelay }}
            timeoutSeconds: {{ .Values.probeTimeout }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probeInitialDelay }}
            timeoutSeconds: {{ .Values.probeTimeout }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- include "proxy-volumes" . | nindent 6}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
