name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  CT_CHART_DIRS: stable

jobs:
  lint-test:

    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "1.19.16"
          - "1.26.14"
          - "1.29.2"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Test
        env:
          KVERSION_LIST: ${{ matrix.k8s }}
        run: ./test.sh true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: |
          helm repo add localstack https://localstack.github.io/helm-charts
          ct lint --check-version-increment=false

      - name: Run chart-testing (list-changed)
        id: changed
        run: |
          since=$(git describe --tags --abbrev=0 || git rev-list --max-parents=0 --first-parent HEAD)
          changed="$(ct list-changed --since "$since")"
          echo "since=$since changed=$changed"
          echo "changed=$changed" >> $GITHUB_OUTPUT
          echo "since=$since" >> $GITHUB_OUTPUT

      - name: Create kind cluster
        if: steps.changed.outputs.changed != ''
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:v${{ matrix.k8s }}   # Test against this kubernetes release
          kubectl_version: v${{ matrix.k8s }}

      - name: Install in kind
        if: steps.changed.outputs.changed != ''
        run: |
          ct install --since ${{ steps.changed.outputs.since }} \
            --helm-extra-set-args "-f examples/local.yaml --set=api.enabled=false"

  compare:

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout base for comparision
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.3

      - name: Compare
        run: |
          ./compare.sh base/stable/vulcan true
